### ISSUE TITLE
Can we use README.md for Github instead of as the index page config of Vuepress?

### ISSUE THREAD

**Issue by mkfsn** [rockylinuxtw/rockylinux.tw#10]
Currently, README.md is used for configuring the index page of the website, and it seems like we can use INDEX.md to replace it and leave README.md to Github as a README for this repo.

See also https://github.com/vuejs/vuepress/pull/23.

**Comment by pwtsai** [comment]
Second.

**Comment by mkfsn** [comment]
https://github.com/vuejs/vuepress/pull/23#issuecomment-584553906

Seems like we have to use `README.markdown`

**Comment by pwtsai** [comment]
How about this (#14)... will it work?

**Comment by mkfsn** [comment]
@pwtsai sorry I just fixed it by this commit: https://github.com/rockylinuxtw/rockylinux.tw/commit/35f541bb71e80fc23a1753b9fdd9fa62f1504dab

**Comment by mkfsn** [comment]
Looks like `index.md` works and `README.md` is better than `README.markdown` so I would like to keep it as it is now.

**Comment by pwtsai** [comment]
okay, thanks!
