### ISSUE TITLE
Failed to deploy to main branch

### ISSUE THREAD

**Issue by mkfsn** [rockylinuxtw/rockylinux.tw#13]
![image](https://user-images.githubusercontent.com/667169/102692783-9fc16280-4250-11eb-8e0d-437172869d08.png)

**Comment by mkfsn** [comment]
I suppose it is caused by the branch protection misconfiguration:
![image](https://user-images.githubusercontent.com/667169/102692848-2c6c2080-4251-11eb-9437-441a24a0d5e9.png)

**Comment by mkfsn** [comment]
Disabled the `Restrict who can push to matching branches` and temporarily solved this issue, closing but we might need to revisit it soon.

**Comment by pwtsai** [comment]
It seems like something went wrong with the auto-building of the `develop` branch...

**Comment by mkfsn** [comment]
@pwtsai I am seeing the build is working, which part that you are saying is not working?

![image](https://user-images.githubusercontent.com/667169/102695193-b8d20f80-4260-11eb-9525-5bf07a7a6146.png)

**Comment by pwtsai** [comment]
I think it should be caused by INDEX.md, could you please have a look?
