### ISSUE TITLE
Add link to Telegram group

### ISSUE THREAD

**Issue by mkfsn** [rockylinuxtw/rockylinux.tw#4]
Link: https://t.me/rockylinuxtw

**Comment by oubayun** [comment]
我们来自中文社区：www.rockylinux.cn，希望我们有更多的互动，微信：rockylinuxcn

**Comment by pwtsai** [comment]
I'd like to suggest to make a `resource list` for summarizing Chinese communities (網站, 電報群, 微信等等). This might be helpful for  `zh` newcomers to get further information.

**Comment by mkfsn** [comment]
In #5, we've added telegram link and link to www.rockylinux.cn, closing.
