### ISSUE TITLE
Add document for how to contribute

### ISSUE THREAD

**Issue by mkfsn** [rockylinuxtw/rockylinux.tw#6]
I assume this is for contributing to the website.

Currently, we have some options:

- [ ] add `CONTRIBUTION.md` in Github
- [ ] add blog post `how-to-contribute.md`

@evshary @pwtsai What do you think?

**Comment by pwtsai** [comment]
I think both of them are required.

**Comment by evshary** [comment]
Both are required because most users get information from the website while some developers may from GitHub.

**Comment by pwtsai** [comment]
Please kindly find this PR (#7), thanks.

**Comment by evshary** [comment]
已新增 CONTRIBUTING.md，這邊我們先以 BSD-3 來發佈
請 @mkfsn  和 @pwtsai 看看有沒有什麼建議

**Comment by pwtsai** [comment]
> I assume this is for contributing to the website.
> 
> Currently, we have some options:
> 
> * [ ]  add `CONTRIBUTION.md` in Github
> * [ ]  add blog post `how-to-contribute.md`
> 
> @evshary @pwtsai What do you think?

Closed due to PR #8 and #12.
