### ISSUE TITLE
PR notification in TW telegram group

### ISSUE THREAD

**Issue by pwtsai** [rockylinuxtw/rockylinux.tw#9]
Is it possible to trigger the notification when there is a new PR? Thanks.

**Comment by mkfsn** [comment]
@pwtsai sure, we can set up a new GitHub action when a new PR is created, the question would be which slack group should we send a notification to?

**Comment by pwtsai** [comment]
Looks like there is no emerging necessary for applying it, I suggest to close this issue.

**Comment by steveyiyo** [comment]
I agree, I will close this issue later.
If there are any comments or ideas, we can restart the discussion.
